networks:
    webnet:
services:
    nginx:
        image: nginx:1.23.1
        container_name: nginx
        restart: always
        volumes: 
            - /Users/wells_lin/Desktop/docker-Nginx-PHP/nginx/conf.d:/etc/nginx/conf.d
            - /Users/wells_lin/Desktop/docker-Nginx-PHP/nginx/html:/usr/share/nginx/html
        ports: 
            - "80:80"
        networks:
            - webnet    

    php:
        image: php:7.1-fpm-alpine3.9
        container_name: php
        restart: always
        volumes:
            - /Users/wells_lin/Desktop/docker-Nginx-PHP/nginx/html:/usr/share/nginx/html
        expose:
            - 9000 
        networks:
            - webnet               
            