services:
  elasticsearch:
          image: elasticsearch:8.1.3
          container_name: elasticsearch
          ports:
              - "9200:9200"
          environment:
              - discovery.type=single-node
              - xpack.security.enabled=false
          networks:
              efk_network:
                  ipv4_address: 172.20.0.8
  kibana:
        image: kibana:8.1.3
        container_name: kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - I18N_LOCALE=zh-CN
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            efk_network:
                ipv4_address: 172.20.0.9
  fluentd:
        build: /Users/wells_lin/Desktop/docker-Nginx-PHP/fluent
        container_name: fluentd
        volumes:
            - /Users/wells_lin/Desktop/docker-Nginx-PHP/EFK/fluent.conf:/fluentd/etc/fluent.conf
        ports:
            - 24224:24224
            - 24224:24224/udp
        depends_on:
            - elasticsearch
        networks:
            efk_network:
                ipv4_address: 172.20.0.10
networks:
  efk_network:
    external:
      name: efk_network