services:
  elasticsearch:
        image: elasticsearch:8.1.3
        container_name: elasticsearch
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        networks:
            efk_network:
  kibana:
        image: kibana:8.1.3
        container_name: kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - I18N_LOCALE=zh-CN
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            efk_network:
  fluentdforward:
        build: /Users/wells_lin/Desktop/docker-Nginx-PHP/EFK/fluent
        container_name: fluentdForward
        volumes:
            - /Users/wells_lin/Desktop/docker-Nginx-PHP/EFK/fluent/fluent.conf:/fluentd/etc/fluent.conf
        ports:
            - 24224:24224
            - 24224:24224/udp
        depends_on:
            - elasticsearch
        networks:
            efk_network:
networks:
  efk_network:
    driver: bridge
    name: efk_network
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1