version: '3.8'
services:
    nginx-prometheus-exporter:
        image: nginx/nginx-prometheus-exporter:0.10
        container_name: nginx-prometheus-exporter
        command: -nginx.scrape-uri http://nginx-server1:8080/stub_status
        ports:
            - 9113:9113
        networks:
            fwa_network:
    prometheus:
        image: prom/prometheus:v2.35.0
        container_name: prometheus
        volumes:
          - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
          - ./prometheus/prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yaml'
        ports:
            - '9090:9090'
        networks:
            fwa_network:
    renderer:
        image: grafana/grafana-image-renderer:3.4.2
        container_name: renderer
        environment:
          BROWSER_TZ: Asia/Taipei
        ports:
            - '8081:8081'
        networks:
            fwa_network:
    grafana:
        image: grafana/grafana:8.2.5
        container_name: grafana
        volumes:
          - ./grafana_data:/var/lib/grafana
        environment:
          GF_SECURITY_ADMIN_PASSWORD: pass
          GF_RENDERING_SERVER_URL: http://renderer:8081/render
          GF_RENDERING_CALLBACK_URL: http://grafana:3000/
          GF_LOG_FILTERS: rendering:debug
        depends_on:
          - prometheus
          - renderer
        ports:
          - '3000:3000'
        networks:
            fwa_network:
networks:
  fwa_network:
    external:
      name: fwa_network